COPY persons(	
      Nama
      ,Tipe
      ,KodeCabang
      ,NamaIbu
      ,TelpRumah
      ,Alamat
      ,Email
      ,CityTown
      ,Postcode
      ,Income
      ,Purpose
      ,Source
      ,IDType
      ,Ponsel
      ,Type
      ,Createdby
      ,IdNumber
      ,mnemonics
      ,documentFlag
      ,countryCode
      ,nationality
      ,email2
      ,email3
      ,email4
      ,target
      ,biOwnership
      ,officerCode
      ,info1
      ,info2
      ,pillar
      ,village
      ,subdistrict
      ,province
      ,occupation
      ,bankRelation
      ,bmpkViolation
      ,bmpkExceed
      ,monthlyDebtFreq
      ,monthlyCredFreq
      ,monthlyDebtAmt
      ,monthlyCredAmt
      ,lbucustypebs2
      ,birthPlace
      ,gender
      ,titleBeforeName
      ,titleAfterName
      ,religion
      ,resident
      ,maritalStatus
      ,spouseName
      ,educationLevel
      ,language
      ,staffOfficial
      ,sidRelation
      ,custStatus
      ,cifBloked
      ,mailingList
      ,mailingListStat
      ,officeName
      ,officeAddress
      ,officePostcode
      ,supervisorId
      ,lastchange
      ,terminalid
      ,IDExpiryDate
      ,CreationDate
      ,TanggalLahir
      ,npwp
      ,domisiliDate
      ,streetname2
      ,pillar2
      ,village2
      ,subdistrict2
      ,citytown2
      ,province2
      ,Postcode2
      ,streetname3
      ,pillar3
      ,village3
      ,subdistrict3
      ,citytown3
      ,province3
      ,Postcode3
      ,OtherBankAccount
      ,OtherBankName
      ,OtherBankAccount2
      ,OtherBankName2
      ,homeOwnership
      ,inherited
      ,employeeCode
      ,staffdesignation
      ,employeeID
      ,custLiability
      ,cifPurpose
      ,ref
      ,phoneOffice
      ,faxOffice
      ,employeeDate
      ,otherBusiness
      ,beneficialJob
      ,relationCode1
      ,relationCode2
      ,custRelated1
      ,custRelated2
      ,bankRelationType
      ,NamaCabang
      ,msgid
      ,trxid
      ,companyEntity
      ,establishDate
      ,namePic
      ,regPlaceCD
      ,info3
      ,info4
      ,info5
      ,info6
      ,info7
      ,info8
      ,info9
      ,info10
      ,dinNoKYC
      ,companyNumberCorp
      ,ministervalidCorp
      ,gopublicCorp
      ,dateoccupiedCorp
      ,sidcodeCorp
      ,lhbucodeCorp
      ,namepic1
      ,positionpic1
      ,phonepic1
      ,mobilephpic1
      ,emailpic1
      ,namepic2
      ,positionpic2
      ,phonepic2
      ,mobilephpic2
      ,emailpic2
      ,bussNaturecorpinf
      ,primeBankcorpinf
      ,bankCodecorpinf
      ,ownerStatuscorpinf
      ,lbucustypebs2CIFBasel2
      ,accostsCorp
      ,typeCorp
      ,payrollBatchID
      ,SIDBursa
      ,name1
      ,position1
      ,address1
      ,idtype1
      ,idnumber1
      ,idvalidto1
      ,mobileph1
      ,gender1
      ,npwp1
      ,citytown1
      ,village1
      ,subdistrict1
      ,name2
      ,position2
      ,address2
      ,idtype2
      ,idnumber2
      ,idvalidto2
      ,mobileph2
      ,gender2
      ,npwp2
      ,name3
      ,position3
      ,address3
      ,idtype3
      ,idnumber3
      ,idvalidto3
      ,mobileph3
      ,gender3
      ,npwp3
      ,name4
      ,position4
      ,address4
      ,idtype4
      ,idnumber4
      ,idvalidto4
      ,mobileph4
      ,gender4
      ,npwp4
      ,citytown4
      ,village4
      ,subdistrict4
      ,citytownp3
      ,villagep3
      ,subdistrictp3
      ,citytownp2
      ,villagep2
      ,subdistrictp2
      ,nameo1
      ,positiono1
      ,addresso1
      ,idtypeo1
      ,idnumbero1
      ,idvalidtoo1
      ,mobilepho1
      ,sharePercentageo1
      ,gendero1
      ,npwpo1
      ,citytowno1
      ,villageo1
      ,subdistricto1
      ,nameo2
      ,positiono2
      ,addresso2
      ,idtypeo2
      ,idnumbero2
      ,idvalidtoo2
      ,mobilepho2
      ,sharePercentageo2
      ,gendero2
      ,npwpo2
      ,citytowno2
      ,villageo2
      ,subdistricto2
      ,nameo3
      ,positiono3
      ,addresso3
      ,idtypeo3
      ,idnumbero3
      ,idvalidtoo3
      ,mobilepho3
      ,sharePercentageo3
      ,gendero3
      ,npwpo3
      ,citytowno3
      ,villageo3
      ,subdistricto3
      ,nameo4
      ,positiono4
      ,addresso4
      ,idtypeo4
      ,idnumbero4
      ,idvalidtoo4
      ,mobilepho4
      ,sharePercentageo4
      ,gendero4
      ,npwpo4
      ,citytowno4
      ,villageo4
      ,subdistricto4
      ,streetname3Corp
      ,citytown3Corp
      ,postcode3Corp
      ,typeBoard
      ,customer_risk
      ,eformdate
      ,AppCode
      ,VirtualAcc
      ,VirtualAccName
      ,TransferDate
      ,HubHukum
      ,HukumLain
      ,OfficePillar
      ,OfficeVillage
      ,OfficeSubdistrict
      ,OfficeCityTown
      ,OfficeProvince
      ,Jabatan
      ,StatusPegawai
      ,JumlahPegawai
      ,NamaDrt
      ,AlamatDrt
      ,PillarDrt
      ,VillageDrt
      ,SubdistrictDrt
      ,CityTownDrt
      ,PostCodeDrt
      ,ProvinceDrt
      ,PhoneDrt
      ,PonselDrt
      ,HubunganDrt
      ,flag_source
      ,sendEmail
      ,Sales_Code
      ,Sales_Name
      ,Sales_Branch_Code
      ,Sales_Branch_Name
      ,Flag_Create_Sales
      ,note_tanpa_npwp
      ,reffNo
      ,data_from
      ,sIUPNo
      ,Commitment
      ,ASO_Code
      ,ASO_Name
      ,birthdatep1
      ,birthdatep2
      ,birthdatep3
      ,birthdatep4
      ,birthdateo1
      ,birthdateo2
      ,birthdateo3
      ,birthdateo4
      ,kodeBidangUsaha
      ,referralCode
      ,usernameOrami
      ,birthplacep1
      ,birthplacep2
      ,birthplacep3
      ,birthplacep4
      ,birthplaceo1
      ,birthplaceo2
      ,birthplaceo3
      ,birthplaceo4
      ,nationality_code1
      ,nationality_code2
      ,nationality_code3
      ,nationality_code4
      ,nationality_codeo1
      ,nationality_codeo2
      ,nationality_codeo3
      ,nationality_codeo4
      ,country_code1
      ,country_code2
      ,country_code3
      ,country_code4
      ,country_codeo1
      ,country_codeo2
      ,country_codeo3
      ,country_codeo4
      ,country_codeAddress1
      ,country_codeAddress2
      ,country_codeAddress3
      ,country_codeAddress4
      ,country_codeAddresso1
      ,country_codeAddresso2
      ,country_codeAddresso3
      ,country_codeAddresso4
      ,country_codeIdentity1
      ,country_codeIdentity2
      ,country_codeIdentity3
      ,country_codeIdentity4
      ,country_codeIdentityo1
      ,country_codeIdentityo2
      ,country_codeIdentityo3
      ,country_codeIdentityo4
      ,source1
      ,source2
      ,source3
      ,source4
      ,sourceo1
      ,sourceo2
      ,sourceo3
      ,sourceo4
      ,pekerjaan1
      ,pekerjaan2
      ,pekerjaan3
      ,pekerjaan4
      ,pekerjaano1
      ,pekerjaano2
      ,pekerjaano3
      ,pekerjaano4
      ,provincen1
      ,provincen2
      ,provincen3
      ,provincen4
      ,provinceo1
      ,provinceo2
      ,provinceo3
      ,provinceo4
      ,post_code1
      ,post_code2
      ,post_code3
      ,post_code4
      ,post_codeo1
      ,post_codeo2
      ,post_codeo3
      ,post_codeo4
      ,faxNo
      ,IncomeLevel
      ,contactPhoneOffice
      ,CustRisk
      ,Street2
      ,PrvPhyAdd2
      ,PoBoxNo2
      ,CRN1
      ,CRN2
      ,CRN3
      ,info3CD
      ,IsPEP
      ,crossSell
      ,full_name
      ,pisahHarta
      ,birthDatePasangan
      ,nikPasangan
      ,jumlahTanggungan
      ,isWorking
      ,groupDebitur
      ,ratingDebitur
      ,lembagaPemeringkat
      ,tanggalPemeringkat
      ,jenisKartuPasangan
      ,kseisid
      ,FirstEstablishCode
      ,FlagBenefOwn
      ,nasabahPrioritas
      ,FirstEstablishDate)
FROM 'C:\Users\LENOVO\Desktop\log\100_nasabah.csv'
DELIMITER ','
CSV HEADER;